catalog:
  image:
    tag: "1.6.2"
  mysql:
    create: false
    endpoint: "bedrock-catalog-mysql.cs1a06u4m3aa.us-east-1.rds.amazonaws.com:3306"
    database: catalog
    secret:
      create: false
      name: catalog-db
      username: catalog_admin

orders:
  image:
    tag: "1.6.2"
  postgresql:
    create: false
    database: orders
    endpoint:
      host: "bedrock-orders-postgres.cs1a06u4m3aa.us-east-1.rds.amazonaws.com"
      port: "5432"
    secret:
      create: false
      name: orders-db
      username: orders_admin
  rabbitmq:
    create: true

carts:
  image:
    tag: "1.6.2"
  dynamodb:
    create: false
    tableName: bedrock-carts
    createTable: false
  serviceAccount:
    create: true
    name: "carts"
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::067514125712:role/bedrock-carts-dynamodb-role"

checkout:
  image:
    tag: "1.6.2"

ui:
  image:
    tag: "1.6.2"
  env:
    - name: RETAIL_UI_THEME
      value: "default"
  endpoints:
    catalog: http://retail-store-catalog:80
    carts: http://retail-store-carts:80
    checkout: http://retail-store-checkout:80
    orders: http://retail-store-orders:80
    assets: http://retail-store-assets:80
